// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// dist_SPD
double dist_SPD(const arma::mat& S1, const arma::mat& S2);
RcppExport SEXP _graph_cpt_dist_SPD(SEXP S1SEXP, SEXP S2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type S1(S1SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type S2(S2SEXP);
    rcpp_result_gen = Rcpp::wrap(dist_SPD(S1, S2));
    return rcpp_result_gen;
END_RCPP
}
// graph_cpt_mean
List graph_cpt_mean(const arma::vec& y, const arma::mat& A, const arma::vec& states, double beta);
RcppExport SEXP _graph_cpt_graph_cpt_mean(SEXP ySEXP, SEXP ASEXP, SEXP statesSEXP, SEXP betaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type A(ASEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type states(statesSEXP);
    Rcpp::traits::input_parameter< double >::type beta(betaSEXP);
    rcpp_result_gen = Rcpp::wrap(graph_cpt_mean(y, A, states, beta));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_graph_cpt_dist_SPD", (DL_FUNC) &_graph_cpt_dist_SPD, 2},
    {"_graph_cpt_graph_cpt_mean", (DL_FUNC) &_graph_cpt_graph_cpt_mean, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_graph_cpt(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
