# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title dist_SPD
#'
#' @description Computing distances between symmetric positive definite matrices (with invariant properties)
#'
#' @name dist_SPD
#'
#' @param S1 a SPD matrix
#' @param S2 a SPD matrix
#'
#' @return the square root of the sum of log(lambda_i)^2 with lambda_i the eigenvalues of "S1^(-1/2) * S2 * S1^(-1/2)"
#'
#' @examples
#' n <- 5
#' p <- 10
#' M1 <- matrix(rnorm(p*n), n, p)
#' M2 <- matrix(rnorm(p*n), n, p)
#' S1 <- M1%*%t(M1)
#' S2 <- M2%*%t(M2)
#' dist_SPD(S1,S2)
#'
#' @export
dist_SPD <- function(S1, S2) {
    .Call(`_graph_cpt_dist_SPD`, S1, S2)
}

#' @title ts_to_SPDts
#'
#' @description Converting a time series into a sequence of SPD matrices (covariance matrices)
#'
#' @name ts_to_SPDts
#'
#' @param data matrix of data, size p x n for p dimensions and n data points
#' @param window_length the number of data points to take for computing each covariance matrix
#'
#' @return A list of SPD matrices
#'
#' @export
ts_to_SPDts <- function(data, window_length) {
    .Call(`_graph_cpt_ts_to_SPDts`, data, window_length)
}

#' @title SPDts_to_dists
#'
#' @description Computing all the distance between a list of SPD matrices of size n (obtained by the raw data) and a list of reference matrices of size d.
#'
#' @name SPDts_to_dists
#'
#' @param SPDts list of SPD matrices of size n
#' @param states list of reference matrices of size d
#'
#' @return A matrix of distances between SPD matrices of size d x n
#'
#' @export
SPDts_to_dists <- function(SPDts, states) {
    .Call(`_graph_cpt_SPDts_to_dists`, SPDts, states)
}

#' @title ts_to_dists
#'
#' @description function combining the functions ts_to_SPDts and SPDts_to_dists
#'
#' @name ts_to_dists
#'
#' @param data matrix of data, size p x n for p dimensions and n data points
#' @param states list of reference matrices of size d
#' @param window_length the number of data points to take for computing each covariance matrix
#'
#' @return A matrix of distances between SPD matrices of size d x n
#'
#' @export
ts_to_dists <- function(data, states, window_length) {
    .Call(`_graph_cpt_ts_to_dists`, data, states, window_length)
}

#' @title graph_cpt_manifold
#'
#' @description change point inference for univariate vector constraint by a graph structure and distances computed on a manifold structure
#'
#' @name graph_cpt_manifold
#'
#' @param dists matrix of distances between data and states, size d x n for d states and n data points
#' @param A transition matrix (filled with O and 1)
#' @param beta penalty value for transition between two different states/nodes
#'
#' @return A list
#'
#' @export
graph_cpt_manifold <- function(dists, A, beta = 0) {
    .Call(`_graph_cpt_graph_cpt_manifold`, dists, A, beta)
}

#' @title graph_cpt_mean
#'
#' @description change point inference for univariate vector constraint by a graph structure and fixed means
#'
#' @name graph_cpt_mean
#'
#' @param y univariate data vector y
#' @param A transition matrix (filled with O and 1)
#' @param states vector of state means, a fixed mean value for each node
#' @param beta penalty value for transition between two different states/nodes
#'
#' @return A list
#'
#' @examples
#' vec <- c(rnorm(5, sd = 1), rnorm(5, mean = 1, sd = 0), rnorm(5, mean = 1.9, sd = 1))
#' states <- c(0,1,2)
#' res <- graph_cpt_mean(y = vec, A = transition_matrix(3),states = c(0,1,2), beta = 0)
#' res
#' @export
graph_cpt_mean <- function(y, A, states, beta = 0) {
    .Call(`_graph_cpt_graph_cpt_mean`, y, A, states, beta)
}

