# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title dist_SPD
#'
#' @description Computing distances between symmetric positive definite matrices (with invariant properties)
#'
#' @name dist_SPD
#'
#' @param S1 a SPD matrix
#' @param S2 a SPD matrix
#'
#' @return the square root of the sum of log(lambda_i)^2 with lambda_i the eigenvalues of "S1^(-1/2) * S2 * S1^(-1/2)"
#'
#' @examples
#' n <- 5
#' p <- 10
#' M1 <- matrix(rnorm(p*n), n, p)
#' M2 <- matrix(rnorm(p*n), n, p)
#' S1 <- M1%*%t(M1)
#' S2 <- M2%*%t(M2)
#' dist_SPD(S1,S2)
#'
#' @export
dist_SPD <- function(S1, S2) {
    .Call(`_graph_cpt_dist_SPD`, S1, S2)
}

#' @title graph.cpt.mean
#'
#' @description change point inference for univariate vector constraint by a graph structure and fixed means
#'
#' @name graph.cpt.mean
#'
#' @param y univariate data vector y
#' @param A transition matrix (filled with O and 1)
#' @param states vector of state means, a fixed mean value for each node
#' @param beta penalty value for transition between two different states/nodes
#'
#' @return A list
#'
#' @examples
#' n <- 5
#' p <- 10
#'
#' @export
graph_cpt_mean <- function(y, A, states, beta = 0) {
    .Call(`_graph_cpt_graph_cpt_mean`, y, A, states, beta)
}

