# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

dist_SPD <- function(S1, S2) {
    .Call(`_graph_cpt_dist_SPD`, S1, S2)
}

